# This file was generated by GoReleaser. DO NOT EDIT.
cask "ktop" do
  version "1.3.0"

  on_macos do
    on_arm do
      sha256 "2b210cf18f6451be2235388d36f7653da472df3eaf6f8907ba30bf483000298f"
      url "https://github.com/miraxmetov/ktop/releases/download/v#{version}/ktop_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7f66263a62b495c9ca10a504bf3d91dc43d18e58534aaac8b775a0a14f1c9170"
      url "https://github.com/miraxmetov/ktop/releases/download/v#{version}/ktop_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1b49cd6810acba1efe477473f31f7cb51bdb7b06199a74cb087e2608a9a02540"
      url "https://github.com/miraxmetov/ktop/releases/download/v#{version}/ktop_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "317f952bcaf501cdeeb622b262a59b0c4ff77f841ae959880525694ae584ab07"
      url "https://github.com/miraxmetov/ktop/releases/download/v#{version}/ktop_linux_amd64.tar.gz"
    end
  end

  name "ktop"
  desc "A terminal window into one Kubernetes namespace"
  homepage "https://github.com/miraxmetov/ktop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ktop"
  bash_completion "completions/ktop.bash"
  fish_completion "completions/ktop.fish"
  zsh_completion "completions/_ktop"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ktop"]
    end
  end

  # No zap stanza required
end
