# This file was generated by GoReleaser. DO NOT EDIT.
cask "ktop" do
  version "1.1.2"

  on_macos do
    on_arm do
      sha256 "a63fef6b73e67ee4a5ac73086839e6a6945af4d56cf44648b5550e6a6f603805"
      url "https://github.com/miraxmetov/ktop/releases/download/v#{version}/ktop_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "334350528a4e4434688f512c5d5c20ad2605893ac9122daa7672658bfb006b97"
      url "https://github.com/miraxmetov/ktop/releases/download/v#{version}/ktop_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0d3bcc1921c9a51262eb6285e22bb8ea4fa4751969005687b72d008a4fd07e24"
      url "https://github.com/miraxmetov/ktop/releases/download/v#{version}/ktop_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "281219bd70dd1444010b633a114173f5d29d30a14f7d031ecb34b2e81096bc1d"
      url "https://github.com/miraxmetov/ktop/releases/download/v#{version}/ktop_linux_amd64.tar.gz"
    end
  end

  name "ktop"
  desc "A terminal window into one Kubernetes namespace"
  homepage "https://github.com/miraxmetov/ktop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ktop"
  bash_completion "completions/ktop.bash"
  fish_completion "completions/ktop.fish"
  zsh_completion "completions/_ktop"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ktop"]
    end
  end

  # No zap stanza required
end
