# This file was generated by GoReleaser. DO NOT EDIT.
cask "ktop" do
  version "1.0.2"

  on_macos do
    on_arm do
      sha256 "52ed1985fe251f15040627df5005702ca668e7e1cf62ecfc48abe9521049db2a"
      url "https://github.com/miraxmetov/ktop/releases/download/v#{version}/ktop_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ddae947529613197077246bde6ddb9af0019f20e354475035459a5ec70d3b233"
      url "https://github.com/miraxmetov/ktop/releases/download/v#{version}/ktop_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "01c27745e626821f76038311d1a78dd1c6d9c629a469fe7199f33a6de66510e6"
      url "https://github.com/miraxmetov/ktop/releases/download/v#{version}/ktop_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0e340699876d37a1c7199e317f73c8c83665fd371a5e0f73c4bef51e4dcf310f"
      url "https://github.com/miraxmetov/ktop/releases/download/v#{version}/ktop_linux_amd64.tar.gz"
    end
  end

  name "ktop"
  desc "A terminal window into one Kubernetes namespace"
  homepage "https://github.com/miraxmetov/ktop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ktop"
  bash_completion "completions/ktop.bash"
  fish_completion "completions/ktop.fish"
  zsh_completion "completions/_ktop"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ktop"]
    end
  end

  # No zap stanza required
end
